config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :memos, except: :show
  resources :users, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 40000 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :memos
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_message, only: [:edit, :update, :destroy]
  before_action :current_user, only: [:index, :edit, :update, :destroy]
  
  def index
    @memos = current_user.memos.all
    
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = current_user.memos.build(memo_params)

    if @memo.save
      redirect_to memos_path
    else
      flash.now[:danger] = 'ノートの作成に失敗しました。'
      render :new
    end
  end

  def edit
  end

  def update
    if @memo.update(memo_params)
      redirect_to memos_path
    else
      flash.now[:danger] = 'ノートの更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @memo.destroy

    flash[:success] = 'ノートを削除しました'
    redirect_to memos_url
  end
  
  private

  def set_message
    @memo = current_user.memos.find_by(id: params[:id])
    unless @memo
      flash[:danger] = 'メモが見つかりません。'
      redirect_to memos_path
    end
  end

  # Strong Parameter
  def memo_params
    params.require(:memo).permit(:title, :content)
  end
  
  def correct_user
    @memo = current_user.memos.find_by(id: params[:id])
    unless @memo
      redirect_to memos_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      redirect_to memos_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if current_user
      redirect_to memos_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザ登録しましたので、ログインしてください。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザ登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm bg-white">
    <div class="container-fluid ps-5 pe-5">
      <% if logged_in? %>
        <%= link_to memos_path do %>
          <%= image_tag 'Puppet_Logo.png', id: "img_logo", alt: "Logo", width: "132", height: "60" %>
        <% end %>
      <% else %>
        <%= link_to root_url do %>
          <%= image_tag 'Puppet_Logo.png', id: "img_logo", alt: "Logo", width: "132", height: "60" %>
        <% end %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        
          <% if logged_in? %>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to memos_path, class: 'nav-link active', 'aria-current': 'page' do %>
                  <i class="bi bi-journal-text"></i> memos
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_memo_path, class: 'nav-link' do %>
                  <i class="bi bi-file-earmark-plus"></i> New
                <% end %>
              </li>
            </ul>
            <div class="btn-group">
              <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
              <ul class="dropdown-menu dropdown-menu-end">
                  <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user), class: 'nav-link' %></li>
                  <li class="dropdown-divider"></li>
                  <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
                </ul>
            </div>
          <% else %>
            <ul class="navbar-nav">
              <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
            </ul>
          <% end %>
        </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Microposts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!--bootstrap-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    
    <!--Quill-->
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <link href="https://cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
    
    <!--Google Icon-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/memos/_form.html.erb
<%= form_with(model: memo) do |f| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% memo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="memo_title">
    <%= f.label :title, 'タイトル', id: 'titleText', class: 'titleArea' %>
    <%= f.text_field :title, id: 'titleBox', class: 'titleArea', spellcheck: 'false', placeholder: 'タイトルを入力してください' %>
  </div>
  
  <div id="memo_content">
    <div id="quill-editor" spellcheck="false"></div>
    <%= f.hidden_field :content, id: 'memo_content_field' %>
  </div>
  

  <%= f.submit '保存', id: 'save' %>
<% end %>


<script>
  // Quillテキストエディタを生成する
  let quill = new Quill('#quill-editor', {
    theme: 'bubble'
  });
  
  // Quillの内容が変更されたときに、f.text_fieldの値を更新する
  quill.on('text-change', function() {
    var quillContent = quill.root.innerHTML;
    document.getElementById('memo_content_field').value = quillContent;
  });
  
  quill.root.innerHTML = '<%= @memo.content.html_safe if @memo.content.present? %>';
</script>

app/views/memos/edit.html.erb
<%= render 'form', memo: @memo %>

<%= link_to 'このメッセージを削除する', @memo, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
<%= link_to '一覧に戻る', memos_path %>

app/views/memos/index.html.erb
<h1>ノート一覧</h1>

<% if @memos.any? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>タイトル</th>
      </tr>
    </thead>
    <tbody>
      <% @memos.each do |memo| %>
        <tr>
          <td><%= link_to memo.title, edit_memo_path(memo) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ノートがありません</p>
<% end %>

app/views/memos/new.html.erb
<%= render 'form', memo: @memo %>
<%= link_to '一覧に戻る', memos_path %>

app/views/toppages/index.html.erb
<div id="top_page">
  <div class="text-center">
    <h1>ー <span class="mincho">ノートを<span id="keyword">迷わず</span>見返す</span> ー</h1>
    <h2>Welcome to Puppet</h2>
    <div class="btn_list">
      <%= link_to 'Windows版 ダウンロード', signup_path, class: 'btn btn-lg btn-primary' %>
      <%= link_to '新規会員登録へ', signup_path, class: 'btn btn-lg btn-custom' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <table>
    <tr>
      <th>ユーザー名</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @user.email %></td>
    </tr>
  </table>
</div>